export type OfferDataTypes = {
  bedrooms: number,
  city: {
    location: {
      latitude: number,
      longitude: number,
      zoom: number,
    },
    name: string,
  },
  description: string,
  goods: string[],
  host: {
    avatarUrl: string,
    avatar_url?: string,
    id: string,
    isPro: boolean,
    is_pro?: boolean,
    name: string,
  },
  id: string,
  images: string[],
  isFavorite: boolean,
  is_favorite?: boolean,
  isPremium: boolean,
  is_premium?: boolean,
  location: {
    latitude: number,
    longitude: number,
    zoom: number,
  },
  maxAdults: number,
  max_adults?: number,
  previewImage: string,
  preview_image?: string,
  price: number,
  rating: number,
  title: string,
  type: string,
}
